# Generated by Django 5.0.7 on 2024-08-31 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BancoDados', '0005_clientes_remove_pedidos_usuarios_idusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='Clientes_idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BancoDados.clientes'),
        ),
    ]
